more workflow

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -1,6 +1,6 @@
 name: overscript
 
-on: [pull_request, push]
+on: [push]
 
 jobs:
   build:
@@ -14,18 +14,24 @@ jobs:
 
       - name: Install Dependencies
         run: |
-          flutter pub global activate very_good_cli
-          very_good --analytics false
-          very_good packages get --recursive
-
-      # - name: 🕵️ Analyze
-      #   run: flutter analyze lib test
+          flutter pub get
 
       - name: Run Tests
-        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
+        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random --reporter json > reports.json
 
-      - name: Check Code Coverage
-        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
         with:
-          path: coverage/lcov.info
-          min_coverage: 0
+          name: Flutter Tests
+          path: reports.json
+          reporter: flutter-json
+      
+      - name: Report code coverage
+        uses: zgosalvez/github-actions-report-lcov@v1
+        with:
+          coverage-files: coverage/lcov.*.info
+          minimum-coverage: 0
+          artifact-name: code-coverage-report
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          working-directory: apps/my-first-app
